#!/bin/bash

### Backup Script

#
# backsinc [-sfnzv*] <directory source> <directory target>
#

src_arg="$(($#-1))"
dst_arg="$(($#-0))"
# --
src_arg="${!src_arg}"
dst_arg="${!dst_arg}"


if [[ ! -z "$src_arg" && ! -z "$dst_arg" && $# > 2 ]]; then
    PREFIX_SRC="$src_arg"/
    PREFIX_DST="$dst_arg"/
    DIR_TAR=
else
    PREFIX_SRC="../"
    PREFIX_DST="/media/$USER/WAVED/"
    DIR_TAR="${PWD##*/}/" # name of the current directory
    #DIR_TAR="workInProgress/"
fi

### Target

### Domains
#NET_USER="dtrckd"
#Domain="domain"
PREFIX_DST_NET="${NET_USER}@${Domain}:~/"


OPTS="-a -u --delete-after --modify-window=10 --fuzzy --progress --stats -h --no-o --no-g --no-p -O --max-size=2G"

if [ -e ".rsync_include" ]; then
    FILTER_F="--exclude-from=.rsync_include"
fi

#FILTER="--size-only"

#COMPRESS="--compress"
NET="0"
FORCE="0"
SIMUL="0" # calc size of each files to be transfered
DOWN="0" # inverse direction of backup
GREPGIT="1" # don't show .git/* files

##############
### Args Parse
NBARG=$#
for i in `seq 1 $NBARG`; do
    arg=$1
    if [ "$arg" == "" ]; then
        continue
    elif [ "$arg/" == "$DIR_TAR" -o "$arg/" == "$PREFIX_SRC" -o "$arg/" == "$PREFIX_DST" ]; then
        continue
    elif [ "$arg" == "-s" ]; then
        OPTS="$OPTS --dry-run" && FORCE="1"
        SIMUL="1"
    elif [ "$arg" == "-v" ]; then
        VERBOSE="-v -i"
    elif [ "$arg" == "-vv" ]; then
        VERBOSE="-vv -i"
    elif [ "$arg" == "--purge" ]; then
        # remove some
        PURGE="1"
    elif [ "$arg" == "-n" -o "$arg" == "--net" ]; then
        PREFIX_DST=$PREFIX_DST_NET
        FILTER_F="--exclude-from=.rsync_include_expe"
        #FILTER_F="--exclude-from=.rsync_include_net"
        NET="1"
    elif [ "$arg" == "--down" ]; then
        # update from backup
        DOWN="1"
    elif [ "$arg" == "-f" ]; then
        # force the backup
        FORCE="1"
    elif [ "$arg" == "-z" -o "$arg" == "--compress" ]; then
        # force the backup
        COMPRESS="--compress"
    elif [ "$arg" == "--safe" ]; then
        # don't remove anything
        OPTS="$OPTS --max-delete=0"
    elif [ "$arg" == "--size" ]; then
        # size only
        OPTS="$OPTS --size-only"
    elif [ "$arg" == "--nogrep" ]; then
        # font grep exclude git files
        GREPGIT="0"
    elif [ "$arg" == "-ss" -o "$arg" == "--size" ]; then
        # simul + size of files
        OPTS="$OPTS --dry-run"
        FORCE="1"
        SIMUL="2"
    elif [ "$arg" == "-exreg" ]; then
        # exclusion regex
        OPTS="--exclude=$2"
        shift
    elif [ "$arg" == "--checksum" ]; then
        OPTS="$OPTS --checksum"
        shift
    elif [ "$arg" == "--make" ]; then
        Make="1"
    else
        echo "PREFIX_SRC=$PREFIX_SRC"
        echo "PREFIX_DST=$PREFIX_DST"
        echo "DIR_TAR=$DIR_TAR"
        echo -e "$0 error for: ($arg)\n[exiting]"
        exit 1
    fi

    shift

done

### Remove some obsolete file before backup
if [ "$PURGE" == "1" ]; then
    echo "[Delete Stage]"
    find "${PREFIX_SRC}/${SRC}" -type f -name "*\~" -print0 -delete
fi

### Inverse the way of backup
if [ "$DOWN" == "1" ]; then
    TMP_SRC="$PREFIX_SRC"
    PREFIX_SRC="$PREFIX_DST"
    PREFIX_DST="$TMP_SRC"
    #FILTER="$FILTER --exclude=/backup.sh"
fi

### Set path target name
DIR_TAR1="$DIR_TAR"
DIR_TAR2="$DIR_TAR"

if [ "$FORCE" == "0" ]; then
    echo "[warning dammages: use -f]"
    echo "${PREFIX_SRC}${DIR_TAR1} --> ${PREFIX_DST}${DIR_TAR2}"
    exit 1
fi

OPTS="$OPTS $VERBOSE $COMPRESS $REMOTE $FILTER $FILTER_F"

PADD=$(echo "--"$a{1..20}e)
echo -e "$PADD\n[ Rsync Stage ...]"
if [ "$SIMUL" == "2" ]; then #XULGet file size
    echo "[ Simulation ]"
    RES=`/usr/bin/rsync ${OPTS} "${PREFIX_SRC}${DIR_TAR1}" "${PREFIX_DST}${DIR_TAR2}"`
    RES2=$RES
    TTT= # sed fuck
    while read line; do
        if [ -e "$line" ]; then
            line2=`du -sh0 "$line"`
            TTT=`echo  "$RES2" | sed -e "s:^${line}$:${line2}:"`
            RES2=$TTT
            #echo "$RES2"
        fi
    done < <(echo "$RES") # if not, the pipe loose variable up propagation
    echo "$RES2"

else
    if [ "$SIMUL" == "1" ]; then
        echo "[ Simulation ]"
    fi
    echo ''
    if [ "${GREPGIT}" == "1" ]; then
        /usr/bin/rsync ${OPTS} "${PREFIX_SRC}${DIR_TAR1}" "${PREFIX_DST}${DIR_TAR2}" | grep -vE "\.git"
    else
        /usr/bin/rsync ${OPTS} "${PREFIX_SRC}${DIR_TAR1}" "${PREFIX_DST}${DIR_TAR2}"
    fi
    echo "/usr/bin/rsync ${OPTS} ${PREFIX_SRC}${DIR_TAR1} ${PREFIX_DST}${DIR_TAR2}"
fi

if [ "$SIMUL" == "0" -a "$Make" == "1" ]; then
    ssh $NET_USER@$Domain "cd /home/ama/adulac/workInProgress/networkofgraphs/process/pymake && make"
fi

echo ''


